In [1]:
import os
import pandas as pd
from pathlib import Path

# Read in Data

In [2]:
PROJ_PATH = Path(os.getcwd()).parent
DATA_PATH = PROJ_PATH / 'Data'

In [3]:
team_stats = pd.read_csv(DATA_PATH / 'Tournament_Team_Data.csv') # Downloaded from Kaggle: https://www.kaggle.com/datasets/nishaanamin/march-madness-data?select=Tournament+Team+Data+%28Including+2023%29.csv
game_results_85_21 = pd.read_csv(DATA_PATH / 'Tournament_Game_Results.csv') # Downloaded from Kaggle: https://www.kaggle.com/datasets/woodygilbertson/ncaam-march-madness-scores-19852021
game_results_22_23 = pd.read_csv(DATA_PATH / 'Tournament_Game_Results_22_23.csv') # Scraped from NCAA.com (see Notebooks/data_collection.ipynb)
game_results_24 = pd.read_csv(DATA_PATH / 'Tournament_Game_Results_24.csv') # Scraped from NCAA.com (see Notebooks/data_collection.ipynb)
game_results_25 = pd.read_csv(DATA_PATH / 'Tournament_Game_Results_25.csv') # Scraped from NCAA.com (see Notebooks/data_collection.ipynb)

In [4]:
game_results = pd.concat([game_results_25, game_results_24, game_results_22_23, game_results_85_21], ignore_index=True)

# Explore Data

### Team Stats

In [5]:
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147 entries, 0 to 1146
Data columns (total 41 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   YEAR                            1147 non-null   int64
 1   SEED                            1147 non-null   int64
 2   TEAM                            1147 non-null   object
 3   ROUND                           1011 non-null   float64
 4   KENPOM ADJUSTED EFFICIENCY      1011 non-null   float64
 5   KENPOM ADJUSTED OFFENSE         1011 non-null   float64
 6   KENPOM ADJUSTED DEFENSE         1147 non-null   float64
 7   KENPOM ADJUSTED TEMPO           1011 non-null   float64
 8   BARTTORVIK ADJUSTED EFFICIENCY  1147 non-null   float64
 9   BARTTORVIK ADJUSTED OFFENSE     1011 non-null   float64
 10  BARTTORVIK ADJUSTED DEFENSE     1011 non-null   float64
 11  BARTHAG                         1011 non-null   float64
 12  ELITE SOS                       1147 non-null   float64
 13  BARTTORVIK ADJUSTED TEMPO       1147 non-null   float64
 14  2PT %                           1011 non-null   float64
 15  3PT %                           1011 non-null   float64
 16  FREE THROW %                    1147 non-null   float64
 17  EFG %                           1147 non-null   float64
 18  FREE THROW RATE                 1147 non-null   float64
 19  3PT RATE                        1147 non-null   float64
 20  ASSIST %                        1147 non-null   float64
 21  OFFENSIVE REBOUND %             1147 non-null   float64
 22  DEFENSIVE REBOUND %             1147 non-null   float64
 23  BLOCK %                         1147 non-null   float64
 24  TURNOVER %                      1147 non-null   float64
 25  2PT % DEFENSE                   1011 non-null   float64
 26  3PT % DEFENSE                   1147 non-null   float64
 27  FREE THROW % DEFENSE            1147 non-null   float64
 28  EFG % DEFENSE                   1147 non-null   float64
 29  FREE THROW RATE DEFENSE         1147 non-null   float64
 30  3PT RATE DEFENSE                1147 non-null   float64
 31  OP ASSIST %                     1147 non-null   float64
 32  OP O REB %                      1011 non-null   float64
 33  OP D REB %                      1011 non-null   float64
 34  BLOCKED %                       1147 non-null   float64
 35  TURNOVER % DEFENSE              1147 non-null   float64
 36  WINS ABOVE BUBBLE               1011 non-null   float64
 37  WIN %                           1147 non-null   float64
 38  POINTS PER POSSESSION OFFENSE   1011 non-null   float64
 39  POINTS PER POSSESSION DEFENSE   1011 non-null   float64
 40  TEAM.1                          1011 non-null   object
dtypes: float64(37), int64(2), object(2)
memory usage: 367.5+ KB

In [6]:
team_stats

,YEAR,SEED,TEAM,ROUND,KENPOM ADJUSTED EFFICIENCY,KENPOM ADJUSTED OFFENSE,KENPOM ADJUSTED DEFENSE,KENPOM ADJUSTED TEMPO,BARTTORVIK ADJUSTED EFFICIENCY,BARTTORVIK ADJUSTED OFFENSE,...,OP ASSIST %,OP O REB %,OP D REB %,BLOCKED %,TURNOVER % DEFENSE,WINS ABOVE BUBBLE,WIN %,POINTS PER POSSESSION OFFENSE,POINTS PER POSSESSION DEFENSE,TEAM.1
0,2025,1,Auburn,NaN,NaN,NaN,93.4663,NaN,35.396,NaN,...,40.2,NaN,NaN,7.5,17.4,NaN,84.84848,NaN,NaN,NaN
1,2025,1,Duke,NaN,NaN,NaN,89.8470,NaN,37.181,NaN,...,51.4,NaN,NaN,9.7,17.7,NaN,91.17647,NaN,NaN,NaN
2,2025,1,Florida,NaN,NaN,NaN,92.1126,NaN,33.693,NaN,...,46.4,NaN,NaN,8.6,17.0,NaN,88.23529,NaN,NaN,NaN
3,2025,1,Houston,NaN,NaN,NaN,87.8253,NaN,36.804,NaN,...,55.0,NaN,NaN,6.6,21.7,NaN,88.23529,NaN,NaN,NaN
4,2025,2,Alabama,NaN,NaN,NaN,96.6919,NaN,31.278,NaN,...,43.8,NaN,NaN,12.2,13.5,NaN,75.75758,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,2008,16,Mississippi Valley St.,64.0,-15.0,92.1,107.1000,62.4,-15.300,90.0,...,50.4,34.5,67.5,9.1,22.9,-10.0,50.00000,0.927,0.997,Mississippi Valley St.
1143,2008,16,Mount St. Mary's,64.0,-1.0,99.0,100.1000,65.2,-1.800,97.3,...,47.8,33.0,70.0,7.5,22.0,-9.5,56.25000,1.006,0.968,Mount St. Mary's
1144,2008,16,Portland St.,64.0,5.8,108.4,102.6000,65.8,3.500,105.3,...,54.8,31.3,66.0,6.3,21.5,-3.4,70.00000,1.088,1.003,Portland St.
1145,2008,16,UT Arlington,64.0,-2.0,101.1,103.1000,68.0,-2.100,99.1,...,56.0,30.5,68.2,7.6,20.8,-7.0,60.71000,1.006,0.971,UT Arlington
1146,2008,16,Coppin St.,68.0,-14.2,92.4,106.7000,62.2,-15.400,90.2,...,60.5,38.5,68.0,11.3,25.2,-13.0,41.18000,0.907,1.013,Coppin St.

### Game Results

In [7]:
game_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2585 entries, 0 to 2584
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YEAR    2585 non-null   int64
 1   ROUND   2585 non-null   int64
 2   WSEED   2585 non-null   int64
 3   WTEAM   2585 non-null   object
 4   WSCORE  2585 non-null   int64
 5   LSEED   2585 non-null   int64
 6   LTEAM   2585 non-null   object
 7   LSCORE  2585 non-null   int64
dtypes: int64(6), object(2)
memory usage: 161.7+ KB

In [8]:
game_results

,YEAR,ROUND,WSEED,WTEAM,WSCORE,LSEED,LTEAM,LSCORE
0,2025,6,1,Florida,65,1,Houston,63
1,2025,5,1,Houston,70,1,Duke,67
2,2025,5,1,Florida,79,1,Auburn,73
3,2025,4,1,Auburn,70,2,Michigan State,64
4,2025,4,1,Houston,69,2,Tennessee,50
...,...,...,...,...,...,...,...,...
2580,1985,1,3,North Carolina State,65,14,Nevada,56
2581,1985,1,4,Ohio State,75,13,Iowa State,64
2582,1985,1,1,Oklahoma,96,16,North Carolina A&T,83
2583,1985,1,7,Notre Dame,79,10,Oregon State,70
2584,1985,1,2,North Carolina,76,15,Middle Tennessee State,57

# Preprocessing

### Drop Columns

In [9]:
# ROUND presents data leakage (we won't know what round ends up being the team's last)
# TEAM.1 is redundant
team_stats.drop(columns=['ROUND', 'TEAM.1'], inplace=True)

### Filter Data

In [10]:
# Drop data from game_results for tournaments before 2008
game_results = game_results.copy()[game_results['YEAR'] >= 2008]
game_results

,YEAR,ROUND,WSEED,WTEAM,WSCORE,LSEED,LTEAM,LSCORE
0,2025,6,1,Florida,65,1,Houston,63
1,2025,5,1,Houston,70,1,Duke,67
2,2025,5,1,Florida,79,1,Auburn,73
3,2025,4,1,Auburn,70,2,Michigan State,64
4,2025,4,1,Houston,69,2,Tennessee,50
...,...,...,...,...,...,...,...,...
1124,2008,1,8,Mississippi State,76,9,Oregon,69
1125,2008,1,3,Stanford,77,14,Cornell,53
1126,2008,1,9,Arkansas,86,8,Indiana,72
1127,2008,1,12,Western Kentucky,101,5,Drake,99
1128,2008,0,16,Mount St. Mary's,69,16,Coppin State,60

### Make Naming Conventions Consistent

In [11]:
# Strip any leading or trailing whitespace from Team Name features
team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: name.strip())
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.strip())
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.strip())

In [12]:
# Replace abbreviation "St." with either "Saint" or "State" where appropriate
common_state_uni = ["Murray St.", "San Diego St.", "Michigan St.", "Kansas St.", "Montana St.", "Iowa St.", "Ohio St.", "New Mexico St.", "Arizona St.", "SE Missouri St.", "Penn St.", "Utah St.", "Boise St.", "Kennesaw St.", "Kent St.", "Mississippi St.", "NM St.", "Colorado St.", "Wright St.", "Norfolk St.", "Cal St. Fullerton", "Georgia St.", "Jacksonville St.", "S. Dakota St."]

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: name.replace("St.", "Saint") if name in ["St. Bonaventure", "Mount St. Mary's", "St. John's"] else name)
team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: name.replace("St.", "State") if "St." in name else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("St.", "State") if name in common_state_uni else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("St.", "Saint") if "St." in name else name)

game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("St.", "State") if name in common_state_uni else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("St.", "Saint") if "St." in name else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "McNeese State" if name == "McNeese" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "McNeese State" if name == "McNeese" else name)

In [13]:
# Make school names consistent between the two datasets
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "USC" if name == "Southern California" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "USC" if name == "Southern California" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "BYU" if name == "Brigham Young" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "BYU" if name == "Brigham Young" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UCF" if name == "Central Florida" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UCF" if name == "Central Florida" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "VCU" if name == "Virginia Commonwealth" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "VCU" if name == "Virginia Commonwealth" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UAB" if name == "Alabama-Birmingham" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UAB" if name == "Alabama-Birmingham" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "SMU" if name == "Southern Methodist" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "SMU" if name == "Southern Methodist" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "California" if name == "UC Berkeley" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "California" if name == "UC Berkeley" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UTSA" if name == "Texas-San Antonio" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UTSA" if name == "Texas-San Antonio" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UMBC" if name == "Maryland-Baltimore County" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UMBC" if name == "Maryland-Baltimore County" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace(" (Cal.)", "") if name == "Saint Mary's (Cal.)" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace(" (Cal.)", "") if name == "Saint Mary's (Cal.)" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace(" (N.Y.)", "") if name == "Albany (N.Y.)" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace(" (N.Y.)", "") if name == "Albany (N.Y.)" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("(Fla.)", "FL") if name == "Miami (Fla.)" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("(Fla.)", "FL") if name == "Miami (Fla.)" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("(FL)", "FL") if name == "Miami (FL)" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("(FL)", "FL") if name == "Miami (FL)" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("(Md.)", "MD") if name == "Loyola (Md.)" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("(Md.)", "MD") if name == "Loyola (Md.)" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("-", " ") if name == "Cal-Poly" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("-", " ") if name == "Cal-Poly" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("-", " ") if name == "Arkansas-Little Rock" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("-", " ") if name == "Arkansas-Little Rock" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("-", " ") if name == "Arkansas-Pine Bluff" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("-", " ") if name == "Arkansas-Pine Bluff" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("-", " ") if name == "Louisiana-Lafayette" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("-", " ") if name == "Louisiana-Lafayette" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Loyola Chicago" if name == "Loyola (Ill.)" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Loyola Chicago" if name == "Loyola (Ill.)" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Southern Miss" if name == "Southern Mississippi" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Southern Miss" if name == "Southern Mississippi" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UT Arlington" if name == "Texas-Arlington" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UT Arlington" if name == "Texas-Arlington" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace("-", " ") if name == "Gardner-Webb" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace("-", " ") if name == "Gardner-Webb" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: f"{name} A&M" if name == 'Prairie View' else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: f"{name} A&M" if name == 'Prairie View' else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "Long Island" if name == "LIU Brooklyn" else name)
                                              
team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: f"{name} State" if name == "Middle Tennessee" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "UConn" if name == "Connecticut" else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UConn" if name == "Connecticut" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UConn" if name == "Connecticut" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "FAU" if name == "Florida Atlantic" else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "FAU" if name == "Florida Atlantic" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "FAU" if name == "Florida Atlantic" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Fairleigh Dickinson" if name == "FDU" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Fairleigh Dickinson" if name == "FDU" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Pittsburgh" if name == "Pitt" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Pittsburgh" if name == "Pitt" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "North Carolina" if name == "N. Carolina" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "North Carolina" if name == "N. Carolina" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Southeast Missouri State" if name == "SE Missouri State" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Southeast Missouri State" if name == "SE Missouri State" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: name.replace(chr(8217), chr(39)))
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: name.replace(chr(8217), chr(39)))

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "UC Santa Barbara" if name == "UCSB" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "UC Santa Barbara" if name == "UCSB" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "NC State" if name == "North Carolina State" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "NC State" if name == "North Carolina State" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "New Mexico State" if name == "NM State" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "New Mexico State" if name == "NM State" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "South Dakota State" if name == "S. Dakota State" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "South Dakota State" if name == "S. Dakota State" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "NC State" if name == "North Carolina State" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "Texas A&M - CC" if name == "Texas A&M CC" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Northern Kentucky" if name == "North Kentucky" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Northern Kentucky" if name == "North Kentucky" else name)

game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Louisiana Lafayette" if name == "Louisiana" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Louisiana Lafayette" if name == "Louisiana" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "College of Charleston" if name in ["Col of Charleston", "Charleston"] else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "College of Charleston" if name in ["Col of Charleston", "Charleston"] else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "College of Charleston" if name in ["Col of Charleston", "Charleston"] else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "Ole Miss" if name == "Mississippi" else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Ole Miss" if name == "Mississippi" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Ole Miss" if name == "Mississippi" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "Texas A&M - CC" if name == "Texas A&M Corpus Chris" else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Texas A&M - CC" if name in ["Texas A&M-CC", "Tex. A&M CC"] else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Texas A&M - CC" if name in ["Texas A&M-CC", "Tex. A&M CC"] else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "American" if name == "American University" else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "American" if name == "American University" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "American" if name == "American University" else name)

team_stats['TEAM'] = team_stats['TEAM'].apply(lambda name: "Omaha" if name == "Nebraska Omaha" else name)
game_results['WTEAM'] = game_results['WTEAM'].apply(lambda name: "Omaha" if name == "Nebraska Omaha" else name)
game_results['LTEAM'] = game_results['LTEAM'].apply(lambda name: "Omaha" if name == "Nebraska Omaha" else name)

### Fix Errors in Dataset

In [14]:
# Correct Auburn's seed from 4 to 5 (YEAR=2019, ROUND=5)
game_results.iloc[336, 5] = 5

# Correct Arkansas's seed from 6 to 8 (YEAR=2023, ROUND=3, LTEAM=Arkansas)
game_results.iloc[146, 5] = 8

# Correct team name from Georgia State to Georgia Tech (YEAR=2021, ROUND=1, WTEAM=Loyola Chicago)
game_results.iloc[305, 6] = 'Georgia Tech'

### Define New Features

In [15]:
# Join Win % to game_results to use as determinant of better/worse seed when the seeds are equal
team_win_pct = team_stats[['YEAR', 'SEED', 'TEAM', 'WIN %']]
game_results = game_results.join(team_win_pct.set_index(['YEAR', 'SEED', 'TEAM']), on=['YEAR', 'WSEED', 'WTEAM'])
game_results = game_results.join(team_win_pct.set_index(['YEAR', 'SEED', 'TEAM']), on=['YEAR', 'LSEED', 'LTEAM'], lsuffix=' WTEAM', rsuffix=' LTEAM')

In [16]:
# Define a team as the better-seeded team or the worse-seeded team & define the target: If an upset occurred
better_seeds = []
better_teams = []
worse_seeds = []
worse_teams = []
upsets = []

for row in game_results.iterrows():
    row = row[1]
    if row['WSEED'] == row['LSEED']:
        if row['WIN % WTEAM'] < row['WIN % LTEAM']:
            better_seeds.append(row['LSEED'])
            better_teams.append(row['LTEAM'])
            worse_seeds.append(row['WSEED'])
            worse_teams.append(row['WTEAM'])
            upsets.append(1)
        else:
            better_seeds.append(row['WSEED'])
            better_teams.append(row['WTEAM'])
            worse_seeds.append(row['LSEED'])
            worse_teams.append(row['LTEAM'])
            upsets.append(0)
    elif row['WSEED'] < row['LSEED']:
        better_seeds.append(row['WSEED'])
        better_teams.append(row['WTEAM'])
        worse_seeds.append(row['LSEED'])
        worse_teams.append(row['LTEAM'])
        upsets.append(0)
    else:
        better_seeds.append(row['LSEED'])
        better_teams.append(row['LTEAM'])
        worse_seeds.append(row['WSEED'])
        worse_teams.append(row['WTEAM'])
        upsets.append(1)

game_results['BETTER_SEED'] = better_seeds
game_results['BETTER_TEAM'] = better_teams
game_results['WORSE_SEED'] = worse_seeds
game_results['WORSE_TEAM'] = worse_teams
game_results['UPSET'] = upsets

In [17]:
game_results = game_results[['YEAR', 'ROUND', 'BETTER_SEED', 'BETTER_TEAM', 'WORSE_SEED', 'WORSE_TEAM', 'UPSET']]
game_results

,YEAR,ROUND,BETTER_SEED,BETTER_TEAM,WORSE_SEED,WORSE_TEAM,UPSET
0,2025,6,1,Florida,1,Houston,0
1,2025,5,1,Duke,1,Houston,1
2,2025,5,1,Florida,1,Auburn,0
3,2025,4,1,Auburn,2,Michigan State,0
4,2025,4,1,Houston,2,Tennessee,0
...,...,...,...,...,...,...,...
1124,2008,1,8,Mississippi State,9,Oregon,0
1125,2008,1,3,Stanford,14,Cornell,0
1126,2008,1,8,Indiana,9,Arkansas,1
1127,2008,1,5,Drake,12,Western Kentucky,1
1128,2008,0,16,Mount Saint Mary's,16,Coppin State,0

In [18]:
num_upsets = game_results.loc[game_results['UPSET'] == 1, :].shape[0]
num_chalk = game_results.loc[game_results['UPSET'] == 0, :].shape[0]

print(f"Upsets from 2008-2025: {num_upsets}\nChalk from 2008-2024: {num_chalk}\nTotal Games: {game_results.shape[0]}")

Upsets from 2008-2025: 337
Chalk from 2008-2024: 792
Total Games: 1129

In [19]:
game_results = game_results.join(team_stats.set_index(['YEAR', 'SEED', 'TEAM']), on=['YEAR', 'BETTER_SEED', 'BETTER_TEAM'])
march_madness_matchups = game_results.join(team_stats.set_index(['YEAR', 'SEED', 'TEAM']), on=['YEAR', 'WORSE_SEED', 'WORSE_TEAM'], lsuffix='_BS', rsuffix='_WS')

march_madness_matchups

,YEAR,ROUND,BETTER_SEED,BETTER_TEAM,WORSE_SEED,WORSE_TEAM,UPSET,KENPOM ADJUSTED EFFICIENCY_BS,KENPOM ADJUSTED OFFENSE_BS,KENPOM ADJUSTED DEFENSE_BS,...,3PT RATE DEFENSE_WS,OP ASSIST %_WS,OP O REB %_WS,OP D REB %_WS,BLOCKED %_WS,TURNOVER % DEFENSE_WS,WINS ABOVE BUBBLE_WS,WIN %_WS,POINTS PER POSSESSION OFFENSE_WS,POINTS PER POSSESSION DEFENSE_WS
0,2025,6,1,Florida,1,Houston,0,NaN,NaN,92.1126,...,43.1,55.0,NaN,NaN,6.6,21.7,NaN,88.23529,NaN,NaN
1,2025,5,1,Duke,1,Houston,1,NaN,NaN,89.8470,...,43.1,55.0,NaN,NaN,6.6,21.7,NaN,88.23529,NaN,NaN
2,2025,5,1,Florida,1,Auburn,0,NaN,NaN,92.1126,...,34.8,40.2,NaN,NaN,7.5,17.4,NaN,84.84848,NaN,NaN
3,2025,4,1,Auburn,2,Michigan State,0,NaN,NaN,93.4663,...,41.4,53.4,NaN,NaN,7.8,16.4,NaN,81.81818,NaN,NaN
4,2025,4,1,Houston,2,Tennessee,0,NaN,NaN,87.8253,...,45.1,46.5,NaN,NaN,9.1,17.8,NaN,79.41176,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,2008,1,8,Mississippi State,9,Oregon,0,15.8,107.3,91.5000,...,35.3,52.9,31.2,67.7,9.7,16.4,0.8,58.06000,1.130,1.065
1125,2008,1,3,Stanford,14,Cornell,0,23.9,113.3,89.4000,...,33.7,54.6,30.9,71.1,7.4,20.6,-1.2,80.77000,1.104,0.995
1126,2008,1,8,Indiana,9,Arkansas,1,19.5,114.4,94.9000,...,34.8,52.3,31.4,62.4,9.8,21.7,0.5,66.67000,1.054,0.960
1127,2008,1,5,Drake,12,Western Kentucky,1,22.3,119.8,97.4000,...,31.6,52.2,32.8,63.0,6.6,25.2,0.2,80.65000,1.106,0.940
1128,2008,0,16,Mount Saint Mary's,16,Coppin State,0,-1.0,99.0,100.1000,...,37.9,60.5,38.5,68.0,11.3,25.2,-13.0,41.18000,0.907,1.013

In [22]:
# Replace the individual team statistics as features with the difference between each team's stats
for bs_col in march_madness_matchups.columns[7:43]:
    ws_col = bs_col.replace("_BS", "_WS")
    
    better_seed_stat = march_madness_matchups[bs_col]
    worse_seed_stat = march_madness_matchups[ws_col]
    march_madness_matchups.drop(columns=[bs_col, ws_col], inplace=True)
    
    col = bs_col[:-3]
    march_madness_matchups[col] = better_seed_stat - worse_seed_stat

In [23]:
march_madness_matchups

,YEAR,ROUND,BETTER_SEED,BETTER_TEAM,WORSE_SEED,WORSE_TEAM,UPSET,KENPOM ADJUSTED EFFICIENCY,KENPOM ADJUSTED OFFENSE,KENPOM ADJUSTED DEFENSE,...,3PT RATE DEFENSE,OP ASSIST %,OP O REB %,OP D REB %,BLOCKED %,TURNOVER % DEFENSE,WINS ABOVE BUBBLE,WIN %,POINTS PER POSSESSION OFFENSE,POINTS PER POSSESSION DEFENSE
0,2025,6,1,Florida,1,Houston,0,NaN,NaN,4.2873,...,-5.8,-8.6,NaN,NaN,2.0,-4.7,NaN,0.00000,NaN,NaN
1,2025,5,1,Duke,1,Houston,1,NaN,NaN,2.0217,...,-5.2,-3.6,NaN,NaN,3.1,-4.0,NaN,2.94118,NaN,NaN
2,2025,5,1,Florida,1,Auburn,0,NaN,NaN,-1.3537,...,2.5,6.2,NaN,NaN,1.1,-0.4,NaN,3.38681,NaN,NaN
3,2025,4,1,Auburn,2,Michigan State,0,NaN,NaN,2.9763,...,-6.6,-13.2,NaN,NaN,-0.3,1.0,NaN,3.03030,NaN,NaN
4,2025,4,1,Houston,2,Tennessee,0,NaN,NaN,-0.7173,...,-2.0,8.5,NaN,NaN,-2.5,3.9,NaN,8.82353,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,2008,1,8,Mississippi State,9,Oregon,0,-0.9,-12.0,-11.1000,...,-0.6,-3.3,1.4,-2.9,-0.8,1.8,-0.2,10.69000,-0.084,-0.134
1125,2008,1,3,Stanford,14,Cornell,0,18.9,2.6,-16.2000,...,-6.7,-9.1,-2.1,-10.3,-1.5,-2.5,7.9,-1.98000,-0.018,-0.064
1126,2008,1,8,Indiana,9,Arkansas,1,4.6,4.7,0.1000,...,0.9,3.8,-2.5,1.5,-1.9,-1.8,4.3,11.46000,0.050,-0.009
1127,2008,1,5,Drake,12,Western Kentucky,1,8.2,8.7,0.4000,...,7.7,4.7,0.1,0.4,3.8,-1.2,5.0,6.02000,0.035,0.024
1128,2008,0,16,Mount Saint Mary's,16,Coppin State,0,13.2,6.6,-6.6000,...,-7.2,-12.7,-5.5,2.0,-3.8,-3.2,3.5,15.07000,0.099,-0.045

In [24]:
march_madness_matchups.to_csv(DATA_PATH / 'march_madness_historical_data.csv', index=False)